---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: "{{ postgres_pv_name }}"
  labels:
    app: postgres
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ postgres_data_path }}"
---
