---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "{{ k8s_namespace | default('default') }}"
  name: postgres
  labels:
    app: postgres
spec:
{% if (k8s_namespace | default('default')) != 'default' %}
  volumeName: "{{ postgres_pv_name }}"
{% endif %}
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
