apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: "{{ k8s_namespace | default('default') }}"
  labels:
    app: postgres
spec:
  ports:
    - port: {{ postgres_port }}
  selector:
    app: postgres
