- name: "deploy hetzner-csi-provider secrets"
  kubernetes.core.k8s:
    state: present
    definition: "{{lookup('template', 'secrets.yml') }}"
  no_log: true
  diff: false
  tags: hetzner-cloud-controller-manager

- name: "Apply HelmChartConfig"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'helm-chart-config.yml') }}"
  tags: hetzner-cloud-controller-manager
