apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: hccm
  namespace: kube-system
spec:
  repo: https://charts.hetzner.cloud
  chart: hcloud-cloud-controller-manager
  version: "{{ hcloud_ccm_chart_version }}"
  targetNamespace: kube-system