- name: "install istioctl"
  shell: "curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.20.2 sh -"
  tags: istio

- name: "install istio"
  shell: "cd istio-1.20.2/bin && ./istioctl install --set profile=minimal -y"
  tags: istio

- name: Apply gateway-api crds
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'gateway-api.yml') }}"

- name: Create namespace istio-ingress
  kubernetes.core.k8s:
    name: istio-ingress
    kind: Namespace
    state: present

- name: Apply gateway
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'gateway.yml') }}"