- name: Set microk8s_master to the first host in the storage group
  set_fact:
    microk8s_main: "{{ groups['hcloud_type_master'][0] }}"
  run_once: true
  changed_when: no

- name: "create join key"
  shell: "microk8s add-node --token-ttl 3600"
  register: join_cluster
  delegate_to: "{{ microk8s_main }}"
  when:
    - inventory_hostname != project_name + '-master-0'

- name: "create persistent var"
  set_fact:
    join_cluster_as_master: "{{ join_cluster.stdout_lines[1] }}"
    join_cluster_as_worker: "{{ join_cluster.stdout_lines[4] }}"
  when:
    - inventory_hostname != project_name + '-master-0'

- name: "Add IP address of all hosts to all hosts. To use it in join cluster command."
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
    state: present
  when: hostvars[item].ansible_host is defined
  loop: "{{ groups.all }}"

- name: "join cluster (master node)"
  shell: "{{ hostvars[inventory_hostname]['join_cluster_as_master'] }}"
  register: join_cluster_result_master
  changed_when: "'already known to dqlite' not in join_cluster_result_master.stdout"
  failed_when: "'already known to dqlite' not in join_cluster_result_master.stdout and join_cluster_result_master.rc != 0"
  when:
    - hcloud_labels.get("type") == "master"
    - inventory_hostname != project_name + '-master-0'
    - "'join_cluster_as_master' in hostvars[inventory_hostname]"

- name: "join cluster (worker node)"
  shell: "{{ hostvars[inventory_hostname]['join_cluster_as_worker'] }}"
  register: join_cluster_result_worker
  when: hcloud_labels.get("type") == "worker"

- name: Wait for microk8s to be ready
  become: yes
  command: "microk8s.status --wait-ready"
  changed_when: false
  register: microk8s_status_out
  failed_when:
    - "'This MicroK8s deployment is acting as a node in a cluster.' not in microk8s_status_out.stdout_lines"
    - microk8s_status_out.rc > 0

- name: Get current microk8s addons state
  command: "microk8s.status --format yaml"
  changed_when: no
  register: microk8s_status
  check_mode: no

- name: Set microk8s addons state fact
  set_fact:
    microk8s_status: "{{ microk8s_status.stdout | from_yaml }}"

- name: Enable microk8s addons
  loop: "{{ microk8s_status.addons }}"
  loop_control:
    label: "{{ item.name }}"
  command: "microk8s.enable {{ item.name }}{% if microk8s_plugins[item.name] != True %}:{{ microk8s_plugins[item.name] }}{% endif %}"
  become: yes
  delegate_to: "{{ microk8s_main }}"
  run_once: true
  when:
    - item.status == 'disabled'
    - item.name in microk8s_plugins
    - microk8s_plugins[item.name]