- name: "install snap"
  apt:
    name: snapd
    state: present
    update_cache: yes
  tags: microk8s

- name: Ensure snapd service is running
  become: yes
  systemd:
    name: snapd
    state: started

- name: "Install microk8s"
  become: yes
  snap:
    name: microk8s
    classic: yes
    channel: "{{ microk8s_version }}"
  register: microk8s_install_result
  retries: 5
  delay: 5
  until: microk8s_install_result is succeeded

- name: "add alias for kubectl"
  shell: "snap alias microk8s.kubectl kubectl"
  tags: microk8s

- include_tasks: join_node.yml