- name: Check if Node already joined
  shell: "microceph status |grep -q '{{ inventory_hostname }}'"
  become: true
  delegate_to: "{{ storage_master_node }}"
  register: microceph_node_already_joined_out
  changed_when: no
  failed_when: no

- name: Check for existing registration token for storage node
  ansible.builtin.shell: |
    microceph cluster sql "select * from internal_token_records where name = '{{ inventory_hostname }}'" | grep -q "{{ inventory_hostname }}"
  delegate_to: "{{ storage_master_node }}"
  register: existing_token
  when:
    - microceph_node_already_joined_out.rc > 0 # when not joined primary master node yet
  changed_when: no
  failed_when: no

# Debug existing tokens to verify
- name: Debug existing tokens output
  debug:
    var: existing_token

- name: Delete token when node not joined but token exists
  shell: microceph cluster sql "DELETE FROM internal_token_records WHERE name = '{{ inventory_hostname }}'"
  when: microceph_node_already_joined_out.rc > 0 and  existing_token.rc == 0
  delegate_to: "{{ storage_master_node }}"

- name: Generate registration token for storage node
  ansible.builtin.shell: microceph cluster add {{ inventory_hostname }}
  when:
    - microceph_node_already_joined_out.rc > 0
  register: new_token_out
  delegate_to: "{{ storage_master_node }}"

# Debug generated tokens
- name: Debug generated tokens output
  debug:
    var: new_token_out

# Join non-primary nodes to the Ceph cluster using the generated tokens
- name: Join storage node to the cluster
  ansible.builtin.shell: microceph cluster join {{ new_token_out.stdout }}
  when: inventory_hostname != storage_master_node and microceph_node_already_joined_out.rc > 0 # when not joined primary master node yet
  register: join_output
  failed_when: >
    join_output.rc != 0 and
    ("already exists" not in join_output.stderr)
  changed_when: join_output.rc == 0



