- debug:
    msg: "Applying for wrapping role {{name}}"

- name: "[{{name}}] Create temporary file for the content which will be applied."
  tempfile:
    state: file
    suffix: .yml
  register: path

- name: "[{{name}}] Copy content into temporary file."
  copy:
    content: "{{kubectl_content}}"
    dest: "{{path.path}}"

- name: "[{{name}}] Apply file {{path.path}}"
  command: kubectl apply -f {{path.path}}