apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: combined-gateway
  namespace: nginx-gateway
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
spec:
  gatewayClassName: nginx-gateway
  listeners:
#    - name: http
#      hostname: {{ base_domain }}
#      port: 80
#      protocol: HTTP
#      allowedRoutes:
#        namespaces:
#          from: All
    - hostname: {{ base_domain }}
      name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: base-domain-secret-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
