apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: "{{ k8s_namespace | default('default') }}"
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: hallo@philipp-lein.de
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
{% if cert_manager_solver == "dns01" %}
    - dns01:
        webhook:
          groupName: acme.hetzner.com
          solverName: hetzner
          config:
            tokenSecretKeyRef:
              name: hetzner
              key: token
{% else %}
    - http01:
        ingress:
          ingressClassName: traefik
{% endif %}
