- name: Add prometheus-community Helm repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts
    state: present

- name: Update Helm repository cache
  command: helm repo update
  register: helm_repo_update_result
  changed_when: "'Update Complete' in helm_repo_update_result.stdout"

- name: Install or upgrade Prometheus using Helm
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/prometheus
    release_namespace: monitoring
    create_namespace: true
    chart_repo_url: https://prometheus-community.github.io/helm-charts
    state: present