apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: hcloud-csi
  namespace: kube-system
spec:
  repo: https://charts.hetzner.cloud
  chart: hcloud-csi
  version: "{{ hcloud_csi_chart_version }}"
  targetNamespace: kube-system
